### ISSUE TITLE
SEO: using next-seo and next/head instead of helmet

### ISSUE THREAD

**Issue by princejoogie** [zomeru/portfolio#2]
NextJS has built in [Head](https://nextjs.org/docs/api-reference/next/head) component to let you define meta tags; and if ever you have dynamic content in your portfolio, you can use getStaticProps/getServerSideProps together with [next-seo](https://github.com/garmeeh/next-seo) no need for react-helmet since next is capable of ssr

**Comment by zomeru** [comment]
Yes, I just ran in some issue with importing fonts in globalStyles with Styled Components and it suggested me to use  React-Helmet instead because I don't want to use css files in my project. Gonna remove the Helmet later.
